config/routes.rb
ProjetoFinal::Application.routes.draw do
    
    resources :degrees, only: [:new, :create, :destroy]
    resources :awards, only: [:new, :create, :destroy]
    resources :orientations, only: [:new, :create, :destroy]
    resources :extension_activities, only: [:new, :create, :destroy]
    resources :administrative_activities, only: [:new, :create, :destroy]
    resources :event_participations, only: [:new, :create, :destroy]
    resources :researches, only: [:new, :create, :destroy]
    resources :publications, only: [:new, :create, :destroy]
    resources :examining_boards, only: [:new, :create, :destroy]

    resources :kudos, only: [:create, :destroy]

    resources :relationships, only: [:create, :destroy] 

    resources :users do
		member do
			get :following, :followers, :htmlpage
		end
	end

    match '/signup', to: 'users#new'
    match '/signin', to: 'sessions#new'
    resources :sessions, only: [:new, :create, :destroy]
    match '/signout', to: 'sessions#destroy', via: :delete

    root to: 'static_pages#home'
    
	match '/contact', to: 'static_pages#contact'

end

app/controllers/static_pages_controller.rb
# encoding: utf-8

class StaticPagesController < ApplicationController
   
    def home
        if signed_in?
            @feed_items = current_user.feed.paginate(page: params[:page])
        end
    end
    
    def contact
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contato') %>

<h1>Futura pagina de contatos</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>

<div class="row">

    <div class="span3">
        <div>
            <h1>
                <%= link_to current_user.name, edit_user_path(current_user) %>
            </h1> 
        </div>

        <div>
            <%= render 'shared/user_info' %>
            <% if current_user?(current_user) %>
            <% end %>
        </div>
        
        <div class="div-stats-user">
            <%= render 'shared/stats' %>
        </div>

        <div class="div-novo-input">
            <%= link_to "Inserir grau ou título", new_degree_path %><br/>
            <%= link_to "Inserir publicação", new_publication_path %><br/>
            <%= link_to "Inserir pesquisa", new_research_path %><br/>
            <%= link_to "Inserir atividade administrativa", new_administrative_activity_path %><br/>
            <%= link_to "Inserir prêmio ou distinção", new_award_path %><br/>
            <%= link_to "Inserir participação em banca examinadora", new_examining_board_path %><br/>
            <%= link_to "Inserir participação em evento", new_event_participation_path %><br/>
            <%= link_to "Inserir atividade de extensão", new_extension_activity_path %><br/>
            <%= link_to "Inserir orientação", new_orientation_path %><br/>
        </div>

        <div class="div-gerador-html">
            <%= link_to "Gerar HTML de publicações", "localhost:3000/users/#{current_user.id}/htmlpage" %>
        </div>
    </div>

    <div class="span9">
        <div class="div-feed-novidades">
            <h3>Novidades</h3>
            <%= render 'shared/feed' %>
        </div>
    </div>
</div>
<% else %>
    <!--	<div class="center hero-unit">
		<h1>Welcome to the Sample App</h1>
		<h2>
			This is the home page for the
			<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
			sample application.
		</h2>
		<%= link_to "Cadastre-se agora!", signup_path, class: "btn btn-large btn-primary" %>
	</div>
<% end %>