config/routes.rb
ProjetoFinal::Application.routes.draw do
    
    resources :degrees, only: [:new, :create, :destroy]
    resources :awards, only: [:new, :create, :destroy]
    resources :orientations, only: [:new, :create, :destroy]
    resources :extension_activities, only: [:new, :create, :destroy]
    resources :administrative_activities, only: [:new, :create, :destroy]
    resources :event_participations, only: [:new, :create, :destroy]
    resources :researches, only: [:new, :create, :destroy]
    resources :publications, only: [:new, :create, :destroy]
    resources :examining_boards, only: [:new, :create, :destroy]

    resources :kudos, only: [:create, :destroy]

    resources :relationships, only: [:create, :destroy] 

    resources :users do
		member do
			get :following, :followers, :htmlpage
		end
	end

    match '/signup', to: 'users#new'
    match '/signin', to: 'sessions#new'
    resources :sessions, only: [:new, :create, :destroy]
    match '/signout', to: 'sessions#destroy', via: :delete

    root to: 'static_pages#home'
    
	match '/contact', to: 'static_pages#contact'

end

app/views/shared/_author_fields.html.erb
    <%= f.label :name, "Autor" %><br />
    <%= f.text_field :name, class: "jade" %><br />
    <%= f.check_box :_destroy %>
    <%= f.label :_destroy, "Remover autor" %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
            <strong><%= object.class.model_name.human %></strong> contém <%= t(:erro, {:count => object.errors.count}) %>
        
		    <ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
            </ul>
        </div>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol>
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
    <%= will_paginate @feed_items, previous_label: 'Anterior', next_label: 'Próximo' %>
<% else %>
    <p>Sem novidades por enquanto...</p>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>" class="feed-item">
	<span class="user">
        <%= link_to feed_item.user.name, feed_item.user %>
    </span>

    <% if current_user.id == feed_item.user.id %>
        <span><%= link_to '<i class="icon-remove"></i>'.html_safe, feed_item, method: :delete, data: {confirm: "Você tem certeza que deseja excluir este input?"} %></span>
    <% end %>
    <br />

    <span><%= render feed_item %></span>
	<span class="timestamp">
    <%= post_time_format(feed_item.created_at) %>
    </span>
    <div><%= render 'shared/give_kudo', input: feed_item %></div>
    
</li>

app/views/shared/_give_kudo.html.erb
<div>
    <div id="kudo_string_<%= input.id %>"><%= decide_kudo_string_for_input input %></div>
    <% if !current_user.gave_kudo_to input %>
        <%= render 'shared/give_kudo_form', input: input %> 
    <% else %>
        <span><%= render 'shared/remove_kudo', input: input %></span>
    <% end %>
</div>

app/views/shared/_give_kudo_form.html.erb
<span>
    <%= form_for(current_user.kudos.build(input_id: input.id), remote: true) do |f| %>
        <div><%= f.hidden_field :input_id %></div>
        <%= f.submit "Dar os parabéns!", class: "bt_give_kudo" %>
        <%= link_to "Parabenizar", '#', class: 'give_kudo_link', id: "kudo_link_#{input.id}" %>
    <% end %>
</span>

app/views/shared/_remove_kudo.html.erb
<%= link_to "(remover parabéns)", input.kudos.find_by_user_id(current_user.id), method: :delete, remote: true, id: "remove_kudo_#{input.id}" %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats"> 

	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
        seguidores
    </a><br/>

    <a href="<%= following_user_path(@user) %>">
		Seguindo <strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
    </a>
</div>

app/views/shared/_user_info.html.erb
<% unless current_user.job_title.blank? %>
    <div>Cargo: <%= current_user.job_title %></div>
<% end %>

<% unless current_user.title.blank? %>
    <div>Título: <%= current_user.title %></div>
<% end %>

<%= image_tag current_user.image_url(:thumb) if current_user.image? %>

<% unless current_user.institution.blank? %>
    <div>Instituição: <%= current_user.institution %></div>
<% end %>

<% unless current_user.homepage.blank? %>
    <div>Homepage: <%= current_user.homepage %></div>
<% end %>